name: SonarQube Analysis

# Trigger the workflow on push or pull request to specific branches
on:
  push:
    branches:
      - main
      - feature1
  pull_request:
    branches:
      - main
      - feature1

jobs:
  sonarqube-scan:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        instance: [1, 2]
        branch: [main, feature1]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java (SonarQube requires Java 11)
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    
    - name: SonarQube Analysis for Instance ${{ matrix.instance }}
      run: |
        if [[ ${{ matrix.instance }} == '1' ]]; then
          sonar-scanner \
            -Dsonar.projectKey=terraform_main \
            -Dsonar.host.url=http://localhost:9001 \
            -Dsonar.login=${{ secrets.SONARQUBE_TOKEN_MAIN }};
        elif [[ ${{ matrix.instance }} == '2' ]]; then
          sonar-scanner \
            -Dsonar.projectKey=terrafrom-feature1 \
            -Dsonar.host.url=http://localhost:9002 \
            -Dsonar.login=${{ secrets.SONARQUBE_TOKEN_FEATURE1 }};
        fi

